version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 850995535715.dkr.ecr.ap-southeast-1.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t test-pipeline .
      - echo Tagging the Docker image...
      - docker tag test-pipeline:latest 850995535715.dkr.ecr.ap-southeast-1.amazonaws.com/test-pipeline:latest

  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 850995535715.dkr.ecr.ap-southeast-1.amazonaws.com/test-pipeline:latest
      - echo Creating imagedefinitions.json file for ECS deployment...
      - printf '[{"name":"test-pipeline","imageUri":"850995535715.dkr.ecr.ap-southeast-1.amazonaws.com/test-pipeline:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
